version: "3.9"
services:
  web:
    build: .
    #image: "ghcr.io/anyproto/any-sync-admin:latest"
    #tty: true
    ports:
      - "8000:5000"
    volumes:
      - ./code:/code
    environment:
      FLASK_DEBUG: "true"
