version: "3.9"
services:
  web:
    image: "ghcr.io/anyproto/any-sync-admin:${ANY_SYNC_ADMIN_VERSION}"
    tty: true
    ports:
      - "8000:5000"
    volumes:
      - ./etc:/etc/any-sync-admin
    environment:
      FLASK_DEBUG: "true"
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
