on:
  release:
    types: [published]

name: push-docker-image-release

jobs:
  push-docker-image-release:
    uses: anyproto/any-sync-node/.github/workflows/push-docker-image-reusable.yml@editWorkflowPush-docker-image-reusable
    secrets: inherit
    with:
      release: ${{ github.event.release.tag_name }}
      dockerfile-image: ubuntu:22.04
      dockerfile-run: apt-get update && apt-get install -y python3
